# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright 2025 Refeyn
#

obj-y += ../../toradex/common/
obj-y += ../../toradex/aquila-am69/ddrs_patch.o
obj-y += ../../toradex/aquila-am69/aquila_ddrs_16GB.o
obj-y += ../../toradex/aquila-am69/aquila_ddrs_8GB.o
obj-y += aquila-am69-refeyn.o
